name: Build

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  IMAGE_NAME: aellwein/cert-backup-operator
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Go 1.25.2
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: 1.25.2

      - name: Build
        run: |
          go build ./...

      - name: Test
        run: go test ./...

      # - name: Login to container registry
      #   uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ env.USERNAME }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0

      # - name: Build & push Docker image (amd64 only for now)
      #   uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6.14.0
      #   with:
      #     platforms: linux/amd64
      #     push: true
      #     context: .
      #     file: deployments/Dockerfile
      #     tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
