name: Build

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  IMAGE_NAME: aellwein/cert-backup-operator
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go 1.24
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: 1.24

      - name: Build
        run: |
          go build ./...

      - name: Test
        run: go test ./...

      # - name: Login to container registry
      #   uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ env.USERNAME }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0

      # - name: Build & push Docker image (amd64 only for now)
      #   uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6.14.0
      #   with:
      #     platforms: linux/amd64
      #     push: true
      #     context: .
      #     file: deployments/Dockerfile
      #     tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
